version: "3.7"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql_server
        environment:
            SA_PASSWORD: "Password1!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
            MSSQL_DATABASE: "default"
        ports:
            - "1433:1433"
        volumes:
            - ./data:/data
